### ISSUE TITLE
[HW] <Suma Aithal>

### ISSUE THREAD

**Issue by sumaaithal** [datastaxdevs/workshop-intro-to-cassandra#212] opened 2021-06-20 10:09 UTC
**Name:** <Suma Aithal>
**Email:** <aithalsuma65@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/sumaaithal>

Attach the homework screenshots below for both step II and step III:
-----------------------------------------
<SCREENSHOT>
![Screenshot (133)](https://user-images.githubusercontent.com/38108871/122670065-a91a9000-d1dd-11eb-91b7-815b6d077384.png)
![Screenshot (135)](https://user-images.githubusercontent.com/38108871/122670068-aae45380-d1dd-11eb-8442-e783bf6cbf09.png)

**Comment by SonicDMG** [comment] 2021-06-21 18:15
Hi there Suma, this looks like a duplicate of https://github.com/datastaxdevs/workshop-intro-to-cassandra/issues/213. Closing this issue.

**Closed by SonicDMG** 2021-06-21 18:15 UTC
Labels: duplicate, homework
