### ISSUE TITLE
[HW] Christian Yamepi Tonag

### ISSUE THREAD

**Issue by cristiano9187** [datastaxdevs/workshop-intro-to-cassandra#231] opened 2021-07-04 08:35 UTC
**Name:** Christian Yamepi Tonag
**Email:** <christian.yamepi@capgemini.com>
**Linkedin Profile:** <https://www.linkedin.com/in/yamepi/>

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

<
<img width="944" alt="senario2" src="https://user-images.githubusercontent.com/76538564/124378779-8e531b80-dcb3-11eb-9808-6b375096cca9.png">
>

**Comment by cristiano9187** [comment] 2021-07-07 16:27
I created a new thread by mistake. Actually Issues number 226 and 231 are always mine

**Comment by SonicDMG** [comment] 2021-07-09 18:29
This is a duplicate of https://github.com/datastaxdevs/workshop-intro-to-cassandra/issues/226

**Closed by SonicDMG** 2021-07-09 18:29 UTC
Labels: accepted, homework
